version: '2'

services:
  nginx:
    depends_on:
      - client
      - node-api
    restart: always
    build: 
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '80:80'
  client:
    build:  
      dockerfile: Dockerfile
      context: ./demo-app-fe/
    ports:
      - '3000:3000'
    volumes:
      - ./demo-app-fe/:/app
      - /demo-app-fe/node_modules

    container_name: client
  #server
  node-api:
    build:
      context: ./demo-app-be/
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - ./demo-app-be/:/app
      - /demo-app-be/node_modules
    container_name: node-api
    links:
      - mongodb
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    container_name: mongodb
    volumes:
      - ./db/:/data/db
      - ./database/mongo-init.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

    env_file:
        - demo-app-be/.env

